#!/usr/bin/env sh

# Remove old config dirs and files.
#cd
rm -rf dotfiles/
rm -rf ~/.config/nvim/ ~/.config/ranger/ ~/.ctags.d/
rm -rf ~/.tmux.conf ~/.gitignore_global

# Clone dotfiles repo.
#git clone --quiet https://github.com/mauroporras/dotfiles.git
git clone --quiet https://github.com/yefriddavid/dotfiles.git

# Create new symlinks.
mkdir -p ~/.config/nvim/
ln -s $(pwd)/dotfiles/init.vim ~/.config/nvim/init.vim
mkdir -p ~/.config/ranger/
ln -s $(pwd)/dotfiles/rc.conf ~/.config/ranger/rc.conf
mkdir -p ~/.ctags.d/
ln -s $(pwd)/dotfiles/general.ctags ~/.ctags.d/general.ctags

ln -s $(pwd)/dotfiles/tmux.conf ~/.tmux.conf
ln -s $(pwd)/dotfiles/gitignore_global ~/.gitignore_global

# Configure Git.
dotfiles/git-config

# Start Neovim.
echo 'Starting Neovim to install plugins...'
nvim
