#!/usr/bin/env sh

# Remove old config
rm -rf ~/.config/nvim/ ~/.config/ranger/ ~/.ctags.d/
rm -rf ~/.tmux.conf ~/.gitignore_global

# Create Symlinks
mkdir -p ~/.config/nvim/
ln -s $(pwd)/dotfiles/init.vim ~/.config/nvim/init.vim
mkdir -p ~/.config/ranger/
ln -s $(pwd)/dotfiles/rc.conf ~/.config/ranger/rc.conf
ln -s $(pwd)/dotfiles/scope.sh ~/.config/ranger/scope.sh
mkdir -p ~/.ctags.d/
ln -s $(pwd)/dotfiles/general.ctags ~/.ctags.d/general.ctags

ln -s $(pwd)/dotfiles/tmux.conf ~/.tmux.conf
ln -s $(pwd)/dotfiles/gitignore_global ~/.gitignore_global


